# Julia es practicidad

[Documentación oficial](https://docs.julialang.org/en/v1/)

In [1]:
println("4")

4


In [16]:
# Numeros

In [18]:
1+1.0

2.0

In [4]:
# Stings

In [19]:
"A"

"A"

In [20]:
"S $ans"

"S A"

In [21]:
"B $(ans * ans)"

"B S AS A"

In [6]:
# Arrays

In [22]:
A = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [23]:
B = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [24]:
C = [ 1 2 
      3 4 ]

2×2 Matrix{Int64}:
 1  2
 3  4

In [29]:
D = [ 1;2;3 ]

3-element Vector{Int64}:
 1
 2
 3

# Iteraciones

In [1]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
x = 0
for i in 1:5, j in 1:0.1:2
    x += i*j
end

In [3]:
x

247.5

In [8]:
[ x*2 for x in range(0,1,20) ]

20-element Vector{Float64}:
 0.0
 0.10526315789473684
 0.21052631578947367
 0.3157894736842105
 0.42105263157894735
 0.5263157894736842
 0.631578947368421
 0.7368421052631579
 0.8421052631578947
 0.9473684210526315
 1.0526315789473684
 1.1578947368421053
 1.263157894736842
 1.368421052631579
 1.4736842105263157
 1.5789473684210527
 1.6842105263157894
 1.7894736842105263
 1.894736842105263
 2.0

In [11]:
[ x*y for x in range(0,1,5), y in 0:3 ]

5×4 Matrix{Float64}:
 0.0  0.0   0.0  0.0
 0.0  0.25  0.5  0.75
 0.0  0.5   1.0  1.5
 0.0  0.75  1.5  2.25
 0.0  1.0   2.0  3.0

# Funciones

In [4]:
f(x) = x^2

f (generic function with 1 method)

In [5]:
function f(x,y)
    x+y
end

f (generic function with 2 methods)

In [7]:
methods(f)

# 2 methods for generic function "f":
[1] f(x) in Main at In[4]:1
[2] f(x, y) in Main at In[5]:1

In [12]:
function f(x ; n=10)
    for i in 1:n
        x += x^i
    end
    x
end

f (generic function with 2 methods)

# Utilidades

In [14]:
?sum

search: sum sum! summary cumsum cumsum! isnumeric VersionNumber issubnormal



```
sum(f, itr; [init])
```

Sum the results of calling function `f` on each element of `itr`.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty `itr` can be specified by `init`. It must be the additive identity (i.e. zero) as it is unspecified whether `init` is used for non-empty collections.

!!! compat "Julia 1.6"
    Keyword argument `init` requires Julia 1.6 or later.


# Examples

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

Note the important difference between `sum(A)` and `reduce(+, A)` for arrays with small integer eltype:

```jldoctest
julia> sum(Int8[100, 28])
128

julia> reduce(+, Int8[100, 28])
-128
```

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

---

```
sum(itr; [init])
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty `itr` can be specified by `init`. It must be the additive identity (i.e. zero) as it is unspecified whether `init` is used for non-empty collections.

!!! compat "Julia 1.6"
    Keyword argument `init` requires Julia 1.6 or later.


See also: [`reduce`](@ref), [`mapreduce`](@ref), [`count`](@ref), [`union`](@ref).

# Examples

```jldoctest
julia> sum(1:20)
210

julia> sum(1:20; init = 0.0)
210.0
```

---

```
sum(A::AbstractArray; dims)
```

Sum elements of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> sum(A, dims=1)
1×2 Matrix{Int64}:
 4  6

julia> sum(A, dims=2)
2×1 Matrix{Int64}:
 3
 7
```

---

```
sum(f, A::AbstractArray; dims)
```

Sum the results of calling function `f` on each element of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> sum(abs2, A, dims=1)
1×2 Matrix{Int64}:
 10  20

julia> sum(abs2, A, dims=2)
2×1 Matrix{Int64}:
  5
 25
```


# Macros

In [2]:
@which sum(1:2)

sum(r::AbstractRange{<:Real}) in Base at range.jl:1312

In [7]:
@show (x=3;sum(1:x);)

begin
    x = 3
    #= In[7]:1 =#
    sum(1:x)
end = 6


6

In [6]:
@time sum(rand(100))

  0.000004 seconds (1 allocation: 896 bytes)


52.10605332891696

In [10]:
@show sum(1:2)

sum(1:2) = 3


3

In [14]:
@doc sum([1,2])

```
sum(itr; [init])
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty `itr` can be specified by `init`. It must be the additive identity (i.e. zero) as it is unspecified whether `init` is used for non-empty collections.

!!! compat "Julia 1.6"
    Keyword argument `init` requires Julia 1.6 or later.


See also: [`reduce`](@ref), [`mapreduce`](@ref), [`count`](@ref), [`union`](@ref).

# Examples

```jldoctest
julia> sum(1:20)
210

julia> sum(1:20; init = 0.0)
210.0
```


In [17]:
# I/O