# Julia es practicidad

## Elementos básicos del lenguaje

[Documentación oficial](https://docs.julialang.org/en/v1/)

### Booleanos

In [45]:
true

true

In [46]:
false

false

In [49]:
true & false

false

### Números

In [6]:
1 + 2

3

In [7]:
1 + 2.0

3.0

In [10]:
1 / 0

Inf

In [12]:
NaN + 1

NaN

In [14]:
2 // 4

1//2

### Caracteres y Cadenas (*Strings*)

In [4]:
'A'

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [5]:
"A"

"A"

In [16]:
saludo = "Hola SciPy Latam"

"Hola SciPy Latam"

In [22]:
desde = "desde Salta!!"

"desde Salta!!"

In [66]:
mensaje = saludo * ", " * desde

"Hola SciPy Latam, desde Salta!!"

In [20]:
"S $ans"

"S A"

In [21]:
"B $(ans * ans)"

"B S AS A"

## Colecciones y Estructuras de Datos

### Arreglos (*Arrays*), Matrices y Vectores

In [22]:
A = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [23]:
B = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [24]:
C = [ 1 2 
      3 4 ]

2×2 Matrix{Int64}:
 1  2
 3  4

In [29]:
D = [ 1;2;3 ]

3-element Vector{Int64}:
 1
 2
 3

### Tuplas, Diccionarios y *Sets*

In [26]:
t = (1,"S")

(1, "S")

In [27]:
d = Dict([t,(2,"S")])

Dict{Int64, String} with 2 entries:
  2 => "S"
  1 => "S"

In [28]:
d2 = Dict("evento"=>"SciPy","lugar"=>"Salta")

Dict{String, String} with 2 entries:
  "lugar"  => "Salta"
  "evento" => "SciPy"

In [29]:
d2["evento"]

"SciPy"

In [31]:
s = Set([1,2,2,1,3,4,4])

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [32]:
s1, s2 = Set(saludo), Set(desde)

(Set(['P', 'H', 'a', 'c', 'o', 'm', 'S', 'L', 'y', 'l', 'i', 't', ' ']), Set(['!', 'd', 'a', 'e', 'S', 's', 'l', 't', ' ']))

In [41]:
'a' ∈ s2

true

In [38]:
s1 ∪ s2 

Set{Char} with 17 elements:
  '!'
  'd'
  'e'
  'o'
  'y'
  'i'
  't'
  's'
  ' '
  'P'
  'H'
  'a'
  'c'
  'm'
  'S'
  'L'
  'l'

In [39]:
s1 ∩ s2

Set{Char} with 5 elements:
  'a'
  'l'
  't'
  'S'
  ' '

### Rangos

In [42]:
r = range(0,1,10)

0.0:0.1111111111111111:1.0

In [44]:
r2 = -1:0.01:1

-1.0:0.01:1.0

## Iteraciones

In [122]:
🐇 = 1

for 🥕 in [1, 2, 3, 4, ]
    🐇 += 🥕 
end

🐇

11

In [54]:
x = 0
for i ∈ 1:5, j ∈ 1:0.1:2
    x += i*j
end

In [55]:
x

247.5

In [56]:
[ x*2 for x in range(0,1,20) ]

20-element Vector{Float64}:
 0.0
 0.10526315789473684
 0.21052631578947367
 0.3157894736842105
 0.42105263157894735
 0.5263157894736842
 0.631578947368421
 0.7368421052631579
 0.8421052631578947
 0.9473684210526315
 1.0526315789473684
 1.1578947368421053
 1.263157894736842
 1.368421052631579
 1.4736842105263157
 1.5789473684210527
 1.6842105263157894
 1.7894736842105263
 1.894736842105263
 2.0

In [83]:
M = [ x*y for x in range(0,1,5), y in 0:3 ]

5×4 Matrix{Float64}:
 0.0  0.0   0.0  0.0
 0.0  0.25  0.5  0.75
 0.0  0.5   1.0  1.5
 0.0  0.75  1.5  2.25
 0.0  1.0   2.0  3.0

## Indexación y *slicing*

In [76]:
mensaje[0]

LoadError: BoundsError: attempt to access 31-codeunit String at index [0]

In [77]:
mensaje[1]

'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)

In [81]:
mensaje[begin+3:end-3]

"a SciPy Latam, desde Salt"

In [82]:
mensaje[[1,3,5]]

"Hl "

In [84]:
M[1,1]

0.0

In [86]:
M[:,2]

5-element Vector{Float64}:
 0.0
 0.25
 0.5
 0.75
 1.0

In [87]:
M[3,1:2]

2-element Vector{Float64}:
 0.0
 0.5

In [89]:
M[[1,2],end-2]

2-element Vector{Float64}:
 0.0
 0.25

## Funciones

In [4]:
f(x) = x^2

f (generic function with 1 method)

In [5]:
function f(x,y)
    x+y
end

f (generic function with 2 methods)

In [7]:
methods(f)

# 2 methods for generic function "f":
[1] f(x) in Main at In[4]:1
[2] f(x, y) in Main at In[5]:1

In [12]:
function f(x ; n=10)
    for i in 1:n
        x += x^i
    end
    x
end

f (generic function with 2 methods)

In [60]:
G(f,y) = f(y+2)

G (generic function with 1 method)

In [61]:
G(x-> x+5, 2)

9

### Funciones útiles

In [62]:
println("4")

4


In [69]:
collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

#### Matemáticas

In [100]:
funciones = [sin, cos, exp, exp10, log, log2, tan]

7-element Vector{Function}:
 sin (generic function with 13 methods)
 cos (generic function with 13 methods)
 exp (generic function with 14 methods)
 exp10 (generic function with 7 methods)
 log (generic function with 23 methods)
 log2 (generic function with 8 methods)
 tan (generic function with 12 methods)

#### Patrones de Programación Funcional

In [68]:
map(println, collect(mensaje))

H
o
l
a
 
S
c
i
P
y
 
L
a
t
a
m
,
 
d
e
s
d
e
 
S
a
l
t
a
!
!


31-element Vector{Nothing}:
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 ⋮
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing

In [71]:
filter(x -> x> 0, -1:0.1:1)

10-element Vector{Float64}:
 0.1
 0.2
 0.3
 0.4
 0.5
 0.6
 0.7
 0.8
 0.9
 1.0

In [99]:
reduce( (x,y) -> x + 2y,  1:9)

89

In [101]:
reducer = [ all, any, sum, prod, max, min ]

6-element Vector{Function}:
 all (generic function with 9 methods)
 any (generic function with 9 methods)
 sum (generic function with 14 methods)
 prod (generic function with 6 methods)
 max (generic function with 12 methods)
 min (generic function with 12 methods)

#### Utilidades

In [98]:
?reduce

search: reduce mapreduce



```
reduce(op, itr; [init])
```

Reduce the given collection `itr` with the given binary operator `op`. If provided, the initial value `init` must be a neutral element for `op` that will be returned for empty collections. It is unspecified whether `init` is used for non-empty collections.

For empty collections, providing `init` will be necessary, except for some special cases (e.g. when `op` is one of `+`, `*`, `max`, `min`, `&`, `|`) when Julia can determine the neutral element of `op`.

Reductions for certain commonly-used operators may have special implementations, and should be used instead: `maximum(itr)`, `minimum(itr)`, `sum(itr)`, `prod(itr)`,  `any(itr)`, `all(itr)`.

The associativity of the reduction is implementation dependent. This means that you can't use non-associative operations like `-` because it is undefined whether `reduce(-,[1,2,3])` should be evaluated as `(1-2)-3` or `1-(2-3)`. Use [`foldl`](@ref) or [`foldr`](@ref) instead for guaranteed left or right associativity.

Some operations accumulate error. Parallelism will be easier if the reduction can be executed in groups. Future versions of Julia might change the algorithm. Note that the elements are not reordered if you use an ordered collection.

# Examples

```jldoctest
julia> reduce(*, [2; 3; 4])
24

julia> reduce(*, [2; 3; 4]; init=-1)
-24
```

---

```
reduce(f, A; dims=:, [init])
```

Reduce 2-argument function `f` along dimensions of `A`. `dims` is a vector specifying the dimensions to reduce, and the keyword argument `init` is the initial value to use in the reductions. For `+`, `*`, `max` and `min` the `init` argument is optional.

The associativity of the reduction is implementation-dependent; if you need a particular associativity, e.g. left-to-right, you should write your own loop or consider using [`foldl`](@ref) or [`foldr`](@ref). See documentation for [`reduce`](@ref).

# Examples

```jldoctest
julia> a = reshape(Vector(1:16), (4,4))
4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

julia> reduce(max, a, dims=2)
4×1 Matrix{Int64}:
 13
 14
 15
 16

julia> reduce(max, a, dims=1)
1×4 Matrix{Int64}:
 4  8  12  16
```


#### Notación de **do**  

In [115]:
filter(1:0.1:10) do x
    s = string(x)
    occursin("9", s) && startswith(s,"9")
end

10-element Vector{Float64}:
 9.0
 9.1
 9.2
 9.3
 9.4
 9.5
 9.6
 9.7
 9.8
 9.9

## Broadcasting

In [59]:
x = rand(10)

10-element Vector{Float64}:
 0.8036975495291241
 0.6265836061198407
 0.21497956964461828
 0.9681135669196467
 0.2834052151602232
 0.8007334709089806
 0.31479121885402317
 0.15381145738011004
 0.9992835833742835
 0.6831922446989733

In [63]:
x .+ 2

10-element Vector{Float64}:
 2.803697549529124
 2.6265836061198407
 2.214979569644618
 2.9681135669196466
 2.283405215160223
 2.8007334709089804
 2.3147912188540234
 2.15381145738011
 2.9992835833742832
 2.683192244698973

In [65]:
x .^ 2

10-element Vector{Float64}:
 0.6459297511191189
 0.39260701545814364
 0.046216215364585284
 0.9372438784538812
 0.08031851598001241
 0.6411740914339433
 0.09909351146760151
 0.023657964421393406
 0.9985676800013485
 0.46675164321682183

In [60]:
b(x) = max(x,0.5)

b (generic function with 1 method)

In [61]:
b.(x)

10-element Vector{Float64}:
 0.8036975495291241
 0.6265836061198407
 0.5
 0.9681135669196467
 0.5
 0.8007334709089806
 0.5
 0.5
 0.9992835833742835
 0.6831922446989733

In [66]:
min.(x,0.5)

10-element Vector{Float64}:
 0.5
 0.5
 0.21497956964461828
 0.5
 0.2834052151602232
 0.5
 0.31479121885402317
 0.15381145738011004
 0.5
 0.5

## Contextos y control de flujo

In [1]:
 y = begin 
    x = 1:3
    o = 1
    for i in x
        o *= i
    end
    o
end

6

In [8]:
o

6

In [12]:
x = 5
z = let 
    o = 5
    if x < 2 && x != 0
        println("$x < 2")
        o /= x
    elseif x == 0
        println("x == 0")
    else
        o += x
    end
    println("o = $o")
    o
end

o = 10


10

In [13]:
o

6

## Macros

In [2]:
@which sum(1:2)

sum(r::AbstractRange{<:Real}) in Base at range.jl:1312

In [7]:
@show (x=3;sum(1:x);)

begin
    x = 3
    #= In[7]:1 =#
    sum(1:x)
end = 6


6

In [6]:
@time sum(rand(100))

  0.000004 seconds (1 allocation: 896 bytes)


52.10605332891696

In [117]:
@edit sum(1:2)

In [14]:
@doc sum([1,2])

```
sum(itr; [init])
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty `itr` can be specified by `init`. It must be the additive identity (i.e. zero) as it is unspecified whether `init` is used for non-empty collections.

!!! compat "Julia 1.6"
    Keyword argument `init` requires Julia 1.6 or later.


See also: [`reduce`](@ref), [`mapreduce`](@ref), [`count`](@ref), [`union`](@ref).

# Examples

```jldoctest
julia> sum(1:20)
210

julia> sum(1:20; init = 0.0)
210.0
```


In [118]:
@macroexpand @time sum(1:2)

quote
    #= timing.jl:216 =#
    while false
        #= timing.jl:216 =#
    end
    #= timing.jl:217 =#
    local var"#32#stats" = Base.gc_num()
    #= timing.jl:218 =#
    local var"#34#elapsedtime" = Base.time_ns()
    #= timing.jl:219 =#
    local var"#35#compile_elapsedtime" = Base.cumulative_compile_time_ns_before()
    #= timing.jl:220 =#
    local var"#33#val" = $(Expr(:tryfinally, :(sum(1:2)), quote
    var"#34#elapsedtime" = Base.time_ns() - var"#34#elapsedtime"
    #= timing.jl:222 =#
    var"#35#compile_elapsedtime" = Base.cumulative_compile_time_ns_after() - var"#35#compile_elapsedtime"
end))
    #= timing.jl:224 =#
    local var"#36#diff" = Base.GC_Diff(Base.gc_num(), var"#32#stats")
    #= timing.jl:225 =#
    Base.time_print(var"#34#elapsedtime", (var"#36#diff").allocd, (var"#36#diff").total_time, Base.gc_alloc_count(var"#36#diff"), var"#35#compile_elapsedtime", true)
    #= timing.jl:226 =#
    var"#33#val"
end

In [119]:
@code_warntype sum([0, 1.5, 1//3])

MethodInstance for sum(::Vector{Float64})
  from sum(a::AbstractArray; dims, kw...) in Base at reducedim.jl:889
Arguments
  #self#::Core.Const(sum)
  a::Vector{Float64}
Body::Float64
1 ─      nothing
│   %2 = Core.NamedTuple()::Core.Const(NamedTuple())
│   %3 = Base.pairs(%2)::Core.Const(Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())
│   %4 = Base.:(var"#sum#738")(Base.:(:), %3, #self#, a)::Float64
└──      return %4



## I/O

In [17]:
io = open("README.md","r") 

IOStream(<file README.md>)

In [18]:
content = read(io,String)

"# Julia es practicidad\r\n\r\n![julia-dots-green-top](../../artefactos/imagenes/julia-dots_green_top.svg)\r\n\r\n## Guia\r\n\r\n```shell\r\n> julia --project=\".\"\r\n```\r\n\r\n```julia-repl\r\njulia> using IJulia\r\njulia> jupyterlab(dir=\".\")\r\n```\r\n\r\n## Uso de Librerias\r\n\r\n- Plots\r\n- DataFrames" ⋯ 276 bytes ⋯ "rlab-plotly\r\n```\r\n\r\n```julia-repl\r\njulia> notebook(dir=\".\")\r\n```\r\n\r\n## Materiales adicionales\r\n\r\n- Lista de diferencias especificas con otros lenguajes como Python, Matlab, R ... [Noteworthy differences](https://docs.julialang.org/en/v2/manual/noteworthy-differences/)\r\n"

In [19]:
close(io)

In [26]:
# ?open

In [38]:
lines = open("README.md","r") do io 
    content = read(io,String)
    lines = split(content,"\r\n")
    filter(x-> length(x) > 0, lines)
end

32-element Vector{SubString{String}}:
 "# Julia es practicidad"
 "![julia-dots-green-top](../../artefactos/imagenes/julia-dots_green_top.svg)"
 "## Guia"
 "```shell"
 "> julia --project=\".\""
 "```"
 "```julia-repl"
 "julia> using IJulia"
 "julia> jupyterlab(dir=\".\")"
 "```"
 "## Uso de Librerias"
 "- Plots"
 "- DataFrames"
 ⋮
 "Conda.pip(\"install\", \"webio_jupyter_extension\")"
 "```"
 "Alternativamente"
 "```shell"
 "> conda activate \"PATH de conda\""
 "> jupyter labextension install jupyterlab-plotly"
 "```"
 "```julia-repl"
 "julia> notebook(dir=\".\")"
 "```"
 "## Materiales adicionales"
 "- Lista de diferencias especifi" ⋯ 110 bytes ⋯ "anual/noteworthy-differences/)"

### Piping

In [120]:
open("README.md","r") |> (io-> read(io, String)) |> (x-> split(x,"\r\n")) |> (l -> filter(x-> length(x) > 0, l)) |> length

67